version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db_service
    hostname:   postgres_db_service
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_database
    ports:
      - "5432:5432"
