version: '3.9'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_db_service
    restart: always
    environment:
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: todo_database
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
